import { jsPDF } from "jspdf";

/**
 * Generates a professional single-page PDF rental agreement.
 */
export const generateRentalAgreement = (booking: any) => {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(30, 30, 30);
    doc.rect(0, 0, 210, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text("RENTAL AGREEMENT", 105, 20, { align: "center" });
    doc.setFontSize(9);
    doc.text(`Booking ID: ${booking.id}`, 105, 28, { align: "center" });

    // Content Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    let y = 45;

    const addCompactSection = (title: string, data: { [key: string]: string }) => {
        doc.setFont("helvetica", "bold");
        doc.text(title, 15, y);
        y += 5;
        doc.line(15, y - 4, 195, y - 4);
        doc.setFont("helvetica", "normal");

        Object.entries(data).forEach(([key, value]) => {
            doc.setFont("helvetica", "bold");
            doc.text(`${key}:`, 20, y);
            doc.setFont("helvetica", "normal");
            doc.text(`${value}`, 60, y);
            y += 6;
        });
        y += 2;
    };

    addCompactSection("BOOKING & RIDER INFO", {
        "Date": booking.date,
        "Rider": booking.rider,
        "Scooter": booking.bike,
        "Amount": booking.amount,
        "Passport/IC": booking.details?.passport || "N/A",
        "Phone": booking.details?.phone || "N/A"
    });

    // Add ID Photos (Compact Row)
    doc.setFont("helvetica", "bold");
    doc.text("IDENTITY DOCUMENTS", 15, y);
    y += 5;

    const photoWidth = 58;
    const photoHeight = 38;
    let x = 15;

    const addIdThumbnail = (imgData: string, label: string) => {
        if (imgData) {
            try {
                doc.setFontSize(7);
                doc.text(label, x, y - 1);
                doc.addImage(imgData, 'JPEG', x, y, photoWidth, photoHeight);
                x += photoWidth + 4;
            } catch (e) {
                doc.text("[Image Error]", x, y + 5);
            }
        }
    };

    if (booking.details) {
        addIdThumbnail(booking.details.idFront, "LICENSE FRONT");
        addIdThumbnail(booking.details.idBack, "LICENSE BACK");
        addIdThumbnail(booking.details.passportImg, "PASSPORT");
    }
    y += photoHeight + 10;

    // Add Signature (Moved after IDs)
    if (booking.details?.signature) {
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.text("DIGITAL SIGNATURE", 15, y);
        y += 2;
        doc.setFillColor(255, 255, 255);
        doc.rect(15, y, 60, 20, 'F');
        doc.addImage(booking.details.signature, 'JPEG', 15, y, 60, 20);
        y += 25;
    }

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text("This document is a legally binding rental agreement generated by Ride Scooter Rentals.", 105, 290, { align: "center" });

    doc.save(`Agreement-${booking.id}.pdf`);
};
